// Generated by CodiumAI

import { render } from "@/utils/test/test-utils";
import Skeleton from ".";

describe("Skeleton", () => {
  // Renders a Skeleton component without crashing
  it("should render Skeleton component without crashing", () => {
    render(<Skeleton />);
  });
});
